######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 12 14:56:22 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
unix:OBJECTS_DIR = objects
unix:MOC_DIR = moc

# Input
HEADERS += ../orm_light/orm_light.h
SOURCES += main.cpp ../orm_light/orm_light.cpp
